### ISSUE TITLE
Page title is "Is it just me or server cooties?"

### ISSUE THREAD

**Issue by Off-By-0ne** [SockDrawer/Discopaedia#1]
Go to a discopædia site (I've only tested with http://discopædia.be). Check page title.

I don't have the creativity at the moment to come up with something witty, but the page should not have the same title as the servercooties websites.

**Comment by RaceProUK** [comment]
The site _is_ still in development, y'know :wink:

**Comment by Off-By-0ne** [comment]
So I should only report issues after the site has reached the v1.0 Gold stable release? :trolleybus:

**Comment by RaceProUK** [comment]
Let me think about that and get back to you… :stuck_out_tongue_winking_eye:

**Comment by AccaliaDeElementia** [comment]
nah. report away. ;-)

we might not exactly jump on them but issue reports are welcome (particularly if the also affect servercooties.com)

**Comment by Off-By-0ne** [comment]
This issue in particular also affects servercooties.com: its page title is also "Is it just me or server cooties?".

I would consider that appropriate though and not an issue ;)

**Comment by AccaliaDeElementia** [comment]
:+1: 

would laugh again!
